update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,8 +24,8 @@ jobs:
       - name: Install Dependencies
         run: |
           pip install -r requirements.txt
-          pip install pytest  
+          pip install pytest
 
       - name: Run test
-        run: pytest 
+        run: pytest || exit 1  # Forces failure on bad code
 
